//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionGen.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SolutionGen.Generator.Model;
    using System;
    
    
    public partial class DotNetSolution : DotNetSolutionBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 7 ".\Templates\DotNetSolution.tt"
            this.Write("Microsoft Visual Studio Solution File, Format Version 12.00\r\n");
            
            #line default
            #line hidden
            
            #line 8 ".\Templates\DotNetSolution.tt"
 foreach (Project project in GetProjects())
{

            
            #line default
            #line hidden
            
            #line 11 ".\Templates\DotNetSolution.tt"
            this.Write("Project(\"{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\") = \"");
            
            #line default
            #line hidden
            
            #line 11 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( project.Name ));
            
            #line default
            #line hidden
            
            #line 11 ".\Templates\DotNetSolution.tt"
            this.Write("\", \"");
            
            #line default
            #line hidden
            
            #line 11 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( project.Name ));
            
            #line default
            #line hidden
            
            #line 11 ".\Templates\DotNetSolution.tt"
            this.Write(".csproj\", \"{");
            
            #line default
            #line hidden
            
            #line 11 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( project.Guid ));
            
            #line default
            #line hidden
            
            #line 11 ".\Templates\DotNetSolution.tt"
            this.Write("}\"\r\nEndProject\r\n");
            
            #line default
            #line hidden
            
            #line 13 ".\Templates\DotNetSolution.tt"

} 
            
            #line default
            #line hidden
            
            #line 15 ".\Templates\DotNetSolution.tt"
            this.Write("Global\r\n    GlobalSection(SolutionConfigurationPlatforms) = preSolution\r\n");
            
            #line default
            #line hidden
            
            #line 17 ".\Templates\DotNetSolution.tt"
 foreach (string configuration in ActiveConfigurations)
{
    foreach (string platform in Solution.TargetPlatforms)
    { 
            
            #line default
            #line hidden
            
            #line 21 ".\Templates\DotNetSolution.tt"
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 21 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( configuration ));
            
            #line default
            #line hidden
            
            #line 21 ".\Templates\DotNetSolution.tt"
            this.Write("|");
            
            #line default
            #line hidden
            
            #line 21 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( platform ));
            
            #line default
            #line hidden
            
            #line 21 ".\Templates\DotNetSolution.tt"
            this.Write(" = ");
            
            #line default
            #line hidden
            
            #line 21 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( configuration ));
            
            #line default
            #line hidden
            
            #line 21 ".\Templates\DotNetSolution.tt"
            this.Write("|Any CPU\r\n");
            
            #line default
            #line hidden
            
            #line 22 ".\Templates\DotNetSolution.tt"
  }
} 
            
            #line default
            #line hidden
            
            #line 24 ".\Templates\DotNetSolution.tt"
            this.Write("    EndGlobalSection\r\n    GlobalSection(ProjectConfigurationPlatforms) = postSolu" +
                    "tion\r\n");
            
            #line default
            #line hidden
            
            #line 26 ".\Templates\DotNetSolution.tt"
 foreach (Project project in GetProjects())
{
    foreach (string configuration in ActiveConfigurations)
    {
        foreach (string platform in Solution.TargetPlatforms)
        { 
            
            #line default
            #line hidden
            
            #line 32 ".\Templates\DotNetSolution.tt"
            this.Write("        {");
            
            #line default
            #line hidden
            
            #line 32 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( project.Guid ));
            
            #line default
            #line hidden
            
            #line 32 ".\Templates\DotNetSolution.tt"
            this.Write("}.");
            
            #line default
            #line hidden
            
            #line 32 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( configuration ));
            
            #line default
            #line hidden
            
            #line 32 ".\Templates\DotNetSolution.tt"
            this.Write("|");
            
            #line default
            #line hidden
            
            #line 32 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( platform ));
            
            #line default
            #line hidden
            
            #line 32 ".\Templates\DotNetSolution.tt"
            this.Write(".ActiveCfg = ");
            
            #line default
            #line hidden
            
            #line 32 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( configuration ));
            
            #line default
            #line hidden
            
            #line 32 ".\Templates\DotNetSolution.tt"
            this.Write("|Any CPU\r\n        {");
            
            #line default
            #line hidden
            
            #line 33 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( project.Guid ));
            
            #line default
            #line hidden
            
            #line 33 ".\Templates\DotNetSolution.tt"
            this.Write("}.");
            
            #line default
            #line hidden
            
            #line 33 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( configuration ));
            
            #line default
            #line hidden
            
            #line 33 ".\Templates\DotNetSolution.tt"
            this.Write("|");
            
            #line default
            #line hidden
            
            #line 33 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( platform ));
            
            #line default
            #line hidden
            
            #line 33 ".\Templates\DotNetSolution.tt"
            this.Write(".Build.0 = ");
            
            #line default
            #line hidden
            
            #line 33 ".\Templates\DotNetSolution.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( configuration ));
            
            #line default
            #line hidden
            
            #line 33 ".\Templates\DotNetSolution.tt"
            this.Write("|Any CPU\r\n");
            
            #line default
            #line hidden
            
            #line 34 ".\Templates\DotNetSolution.tt"
      }
    }
} 
            
            #line default
            #line hidden
            
            #line 37 ".\Templates\DotNetSolution.tt"
            this.Write("    EndGlobalSection\r\nEndGlobal\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class DotNetSolutionBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
